### ISSUE TITLE
ID-input valdiation

### ISSUE THREAD

**Issue by dsterle** [dsterle/cranach_erweiterte_interaktion#1]
Wenn der Nutzer bei der Startseite auf "Ok" tippt, soll das input-Feld, indem der Nutzer die ID des Transponders eingeben kann ausgewertet werden. Es soll geprüft werden, ob die eingegebene ID vorhanden ist. Ist dies nicht der Fall, soll dies entsprechend angezeigt werden.

**Comment by dsterle** [comment]
Es wird nun geprüft, ob überhaupt eine ID angegeben wurde und ob die eingegebene ID in einem Array names "ids" vorhanden ist. DIeses befindet sich in den "props" der component "inputField". Sollte alles stimmen, so wird der Nutzer zur Website /waiting weitergeleitet

**Comment by dsterle** [comment]
Vorschlag: Soll der Nutzer vor der Weiterleitung oder anschließend eine Bestätigung erhalten, dass die ID übereinstimmt und übernommen wurde?

**Comment by hendrikpawlowski** [comment]
Braucht der Nutzer denn eine Bestätigung? Wenn die ID erkannt wurde wird er doch weitergeleitet

**Comment by dsterle** [comment]
hast recht 💃 🍡 👯‍♂
